# ============================
# Projeto: FastLocation
# Finalidade: Consulta de CEP e endereços
# ============================

name: fast_location_project
description: "App para consulta de endereços"
publish_to: 'none' # Projeto privado, não será publicado no pub.dev

version: 1.0.0+1

# Ambiente de SDK Dart
environment:
  sdk: ^3.9.2

# ============================
# DEPENDÊNCIAS FUNCIONAIS
# ============================
dependencies:
  flutter:
    sdk: flutter

  # Ícones padrão para iOS
  cupertino_icons: ^1.0.8

  # Comunicação HTTP com API ViaCEP
  dio: ^4.0.6

  # Gerenciamento de estado reativo com MobX
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1

  # Armazenamento local com Hive
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # Manipulação de caminhos e diretórios
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_ios: ^2.0.9

  # Abrir mapas para traçar rotas
  map_launcher: ^2.2.1+1

  # Obter coordenadas geográficas a partir de endereços
  geocoding: ^2.1.1

# ============================
# DEPENDÊNCIAS DE DESENVOLVIMENTO
# ============================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Boas práticas de código
  flutter_lints: ^5.0.0

  # Geração automática de código MobX
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5

  # Geração de modelos Hive
  hive_generator: ^2.0.0

  #Analisador estático para detectar problemas no código
  analyzer: ^6.4.1  # Recomendado para evitar avisos do MobX


# ============================
# CONFIGURAÇÕES DO FLUTTER
# ============================
flutter:
  uses-material-design: true

  # Aqui você pode adicionar imagens e fontes personalizadas
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
